version: '2'

services:
  mongodb:
    image: 'bitnami/mongodb:3.6'
    labels:
      kompose.service.type: nodeport
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami'
  sails:
    build:
      context: .
      dockerfile: ./turniej-api/Dockerfile
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
    ports:
      - 1337:1337
    links:
      - mongodb
  apache:
    build:
      context: .
      dockerfile: ./front/Dockerfile
    depends_on:
      - mongodb
    volumes:
      - ./front/dist/front:/usr/local/apache2/htdocs/
    ports:
      - 80:80
volumes:
  mongodb_data:
    driver: local
